spring:
  servlet:
    multipart:
      location: /usr/local/tomcat8/upload

#security:
#  require-ssl: false
    
logging:
#  config: classpath:/log4j-alpha.xml
  file : /var/log/eney_service

eney:
  portal:
    portal-url: http://210.103.187.16:8080
    portal-domain: 210.103.187.16:8080
    api-token-len: 32
    mail-host: localhost
    mail-port: 25
    file-properties:
      fileLocation: /usr/local/tomcat8/upload
    payment-properties:
      service-id: glx_api
      giftcard-commission: 12
      payment-request-url-prefix: http://tpay.billgate.net/
      payment-request-url-suffix: /certify.jsp
      return-url-prefix: http://210.103.187.16:8080/payment/
      return-url-suffix: /return
    user-certify-properties:
      okurl: http://210.103.187.16:8080/userCertify/return